### ISSUE TITLE
Hosting Blog on Compiler.la

### ISSUE THREAD

**Issue by laneymangan** [compilerla/compiler.la#114] opened 2023-08-23 17:47 UTC
The blog committee (Meryl, Anthony, Laney) are trying to nail down the details of where our blog will live. We originally planned to use the platform "Ghost" but also threw around the idea of hosting it on our Compiler website, `compiler.la/blog`. Before getting too ahead of ourselves, we thought we'd check in here to see if hosting it on Compiler's website is even a feasible option. Let me know if there is any information needed to evaluate the feasibility of this.

**Comment by machikoyasuda** [comment] 2023-08-23 18:08
Hey @laneymangan -

I've done both before: host Ghost on the company's private servers (which makes it _free_, because it doesn't require paying Ghost the company for hosting space), and also manage a blog on Jekyll. The compiler.la site uses Jekyll: https://jekyllrb.com/ - and was designed for light-weight blogging. Jekyll has a lot of free blog themes: https://jekyllthemes.io/free - but of course, the engineers can code whatever theme you'd like.

The main questions I would have is:

- Do you want comments on the blog posts?
- Do you want the blog writer themselves to be able to post using a Content Management System (CMS) like Ghost's (or WordPress or what have you), that allows users to log in (like at compiler.la/blog/admin) and post it themselves, _or_, are you okay with blog writers send Engineering a post (Markdown file would be best), and the engineers post it to the website?

If you don't want comments, and you don't need your own CMS, then engineers can host the blog on this Jekyll app. It would require engineers to take 5-10 minutes to upload each post. If y'all are up for it, we can even train you on how to upload your own Markdown files to create blogposts yourself. It's not too difficult, and it's a great technical skill to learn.

**Comment by angela-tran** [comment] 2023-08-23 20:21
+1 to @machikoyasuda's comments that Jekyll has great support for blogging and that using it would integrate well with the current site and not have any extra hosting costs.

> Do you want the blog writer themselves to be able to post using a Content Management System (CMS) like Ghost's (or WordPress or what have you), that allows users to log in (like at compiler.la/blog/admin) and post it themselves, or, are you okay with blog writers send Engineering a post (Markdown file would be best), and the engineers post it to the website?

I have experience setting up [Decap CMS](https://decapcms.org) which is pretty lightweight and integrates with static site generators, including Jekyll. I did it in a side personal project -- see ThisDallasLife/thisdallaslife.com#9. There's a [demo of Decap CMS](https://cms-demo.netlify.com/) if you want to poke around. It's basically a frontend to creating the Markdown files that get commited to our repo.

I noticed that trailangeles/trailangeles also [uses Decap CMS](https://github.com/trailangeles/trailangeles/tree/main/src/admin) 😄 

This is just an option if we really want a CMS. I'm also fine with the approach of just uploading Markdown files in the GitHub UI if everyone else is too.

**Comment by laneymangan** [comment] 2023-08-24 18:26
@machikoyasuda @angela-tran This is all extremely helpful, thank you! We have a blog committee meeting later today so I will run this all by the team, particularly the 3 questions Machiko raised, and circle back. For now, I'll speak for myself in saying this is sounding more and more like the direction we should go, and I'd be more than happy to be trained on uploading markdown/creating the blogposts.

**Comment by laneymangan** [comment] 2023-08-25 21:04
Hi, all! (@machikoyasuda @angela-tran @AnthonyRollins @MerylGreen @thekaveman) The blog committee discussed this and we all agree that hosting the blog on compiler.la seems like the best course of action! 

- We don't think comments on the blog are necessary
- We are good with google analytics
- We are happy to use markdown (this is a skill some of us would like to work on anyway and it seems like a good opportunity. Although, we'd like to keep Decap CMS in mind, if the blog should move in a direction where markdown becomes unmanageable for any reason) 

We're excited about this! We were hoping to release our first blog post in late September, but we realize this doesn't leave a lot of time to get things set up. What would a realistic timeline look like and/or what would be the recommended next steps from the engineers stand point?

**Comment by machikoyasuda** [comment] 2023-08-25 21:38
@laneymangan We need the design for the blog home page and each post page at least a week before publishing.

**Comment by AnthonyRollins** [comment] 2023-09-28 02:10
@laneymangan I am closing out this issue as we have moved into dev for the Blog.

**Closed by AnthonyRollins** 2023-09-28 02:10 UTC
